### ISSUE TITLE
Calendar not visible on Microsoft Edge

### ISSUE THREAD

**Issue by OliviaLundelius** [rcos/observatory-new#29] opened 2019-06-06 20:46 UTC
**Describe the bug**
Calendar not visible at all for Edge users, console error:
`SCRIPT1028: SCRIPT1028: Expected identifier, string or number     calendar (105,17)`

**Comment by rushsteve1** [comment] 2019-12-10 20:38
This is caused by the use of the spread `...` operator in some of our JavaScript files.

Also Edge doesn't support WEBP files.

I'm going to mark this as WONTFIX since Edge is being outmoded anyway.

**Closed as completed by rushsteve1** 2019-12-10 20:38 UTC
Labels: bug, wontfix
